### ISSUE TITLE
Establish an origo

### ISSUE THREAD

**Issue by nicjar** [neicnordic/heirsofdoom#8]
@nicjar commented on [Wed Jan 25 2017](https://github.com/neicnordic/ahm17.neic.nordforsk.org/issues/9)

**Comment by yohell** [comment]
Origo is the corner closest to the door. X axis is along the long wall, in the direction of the windows. Y axis is along short wall, in the direction of the main room.

**Comment by viklund** [comment]
Origo is the North corner.

**Comment by yohell** [comment]
Initially we assume convex obstacles; ie alternate going negative x and y until hitting walls in both directions.

**Comment by viklund** [comment]
It's done
